# Generated by Django 5.2.8 on 2026-03-18 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('GRADUATION', 'Graduation'), ('VALENTINE', 'Valentine'), ('OTHER', 'Other')], max_length=20)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('ACOUSTIC', 'Acoustic'), ('JAZZ', 'Jazz'), ('OTHER', 'Other')], max_length=20)),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('ROMANTIC', 'Romantic'), ('EMOTIONAL', 'Emotional'), ('FUN', 'Fun'), ('INSPIRATIONAL', 'Inspirational')], max_length=20)),
                ('voice_type', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DUET', 'Duet')], max_length=20)),
                ('custom_lyrics', models.TextField(blank=True, max_length=1500, null=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('audio_file_reference', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='generation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='music.songgeneration'),
        ),
        migrations.AddField(
            model_name='songgeneration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_generation', to='music.user'),
        ),
        migrations.AddField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.user'),
        ),
    ]
