# Generated by Django 5.2.8 on 2026-03-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='voice_type',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('CHILD', 'Child'), ('CHOIR', 'Choir'), ('INSTRUMENTAL', 'Instrumental'), ('DUET', 'Duet')], default='MALE', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('ENERGETIC', 'Energetic'), ('CALM', 'Calm')], max_length=50),
        ),
    ]
